[#537] Update participant signature for smdb
episphere/dashboard pull request #561
Opened 2023-08-21 16:24 UTC by jhflorey

This Pr addresses comment https://github.com/episphere/connectApp/issues/537#issuecomment-1681270458 of issue https://github.com/episphere/connectApp/issues/537

2023-08-21 19:06 UTC, abhinavjonnada82 commented on siteManagerDashboard/participantSummary.js
> +    const mddileNameCID = type === 'hipaarevoc' ? fieldMapping.HIPAARevocMiddleName : type === 'datadestruction' ? fieldMapping.dataDestructionMiddleName : fieldMapping.consentMiddleName;
Shouldn't this be 
const suffixCID = type === 'hipaarevoc' ? participant[fieldMapping.HIPAARevocSuffix] : type === 'datadestruction' ? participant[fieldMapping.dataDestructionSuffix] : participant[fieldMapping.consentSuffix];

2023-08-21 19:13 UTC, abhinavjonnada82 commented on siteManagerDashboard/participantSummary.js
> +    const middleName = (participant[mddileNameCID] !== undefined && participant[mddileNameCID] !== "") ? participant[mddileNameCID] : ``
`(participant[mddileNameCID] !== undefined && participant[mddileNameCID] !== "") ? participant[mddileNameCID] : ```

Can be simplified to` participant[mddileNameCID] || ```
Returns an empty string `` if the participant[mddileNameCID] is falsy (which includes undefined and an empty string).

2023-08-21 19:15 UTC, abhinavjonnada82 commented on siteManagerDashboard/participantSummary.js
> +    const suffix = (participant[suffixCID] !== undefined && participant[suffixCID] !== "") ? fieldMapping[participant[suffixCID]] : ``
Same as above

2023-08-21 19:16 UTC, abhinavjonnada82 commented
Minor suggestions. Looks good!

2023-08-22 14:38 UTC, abhinavjonnada82 approved these changes

2023-08-22 14:41 UTC, jhflorey commented on siteManagerDashboard/participantSummary.js
> +    const middleName = (participant[mddileNameCID] !== undefined && participant[mddileNameCID] !== "") ? participant[mddileNameCID] : ``
Solved

2023-08-22 14:42 UTC, jhflorey commented on siteManagerDashboard/participantSummary.js
> +    const suffix = (participant[suffixCID] !== undefined && participant[suffixCID] !== "") ? fieldMapping[participant[suffixCID]] : ``
Solved

2023-08-22 14:42 UTC, jhflorey commented
@abhinavjonnada82 please help re-check again.

2023-08-22 15:14 UTC, anthonypetersen requested changes
fix spelling of variable, looks fine besides that

2023-08-22 15:14 UTC, anthonypetersen commented on siteManagerDashboard/participantSummary.js
> +    const mddileNameCID = type === 'hipaarevoc' ? fieldMapping.HIPAARevocMiddleName : type === 'datadestruction' ? fieldMapping.dataDestructionMiddleName : fieldMapping.consentMiddleName;
please fix spelling of `middle`

2023-08-22 15:53 UTC, anthonypetersen approved these changes

2023-08-22 16:14 UTC, merged